### ISSUE TITLE
mac运行weide失败的Error，已附解决方法

### ISSUE THREAD

**Issue by jmolboy** [i5ting/stuq-wxapp#1]
```
$ weide
complete!
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Applications/微信web开发者工具.app/Contents/Resources/app.nw/app/dist/weapp/appservice/asdebug.js'
    at Error (native)

```

失败原因是0.7的IDE目录是
/Applications/微信web开发者工具.app/*
而0.9的目录是
/Applications/wechatwebdevtools.app/*

0.9和0.7的CFBundleDisplayName不一样；可以查看：

more /Applications/wechatwebdevtools.app/Contents/Info.plist

所以需要设置WECHAT_IDE的环境变量：
mac

> $ export WECHAT_IDE=/Applications/wechatwebdevtools.app/
> $ weide

运行成功！

windows因为都是基于nw.js所以应该是一样

> $ export WECHAT_IDE=/Applications/wechatwebdevtools.app/
> $ weide

**Comment by i5ting** [comment]
thanks
